name: Publish Package to Packagist
on:
  push:
    branches:
        - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install
      - name: Publish to Packagist
        run: composer config http-basic.packagist.org ${{ secrets.PACKAGIST_USERNAME }} ${{ secrets.PACKAGIST_API_TOKEN }}
      - run: composer require crafterlp/activeserverssdk --no-update
      - run: composer update crafterlp/activeserverssdk --lock
